_posts/2019-08-18-introducing-the-rust-game-development-working-group.md
_sass/extra.scss
assets/css/style.scss

I tried my best not to make it overlap too much with what @ozkriff is working on for the newsletter 😄 Let me know if the content seems right/if there's anything obvious I've missed.
I also tweaked a couple of style things for readability because they would have driven me crazy otherwise...

First draft of an introduction post

---

README.md
newsletter-template.md

Closes #15 (_"Newsletter: Create template and document workflow"_)

Add a newsletter template and document the workflow

---

_config.yml

This PR excludes the template file to fix this:
_Follow up to #21_

Quickfix: Exclude the template file

---

_drafts/newsletter-003.md

Ok, let's start working on the newsletter earlier this time)
This draft uses [an updated structure with separate "Game Updates" and "Library & Tooling Updates" sections](https://github.com/rust-gamedev/rust-gamedev.github.io/pull/25#pullrequestreview-297792735).
I haven't deleted `Other News` sections for oneliners for now, but one-liner news format doesn't make much sense with the new post structure that is already more granular, so they most likely will be removed before publishing.

Newsletter 3: Initial Draft

---

content/posts/_index.md
templates/includes/home.html

As noticed by @ozkriff, the homepage wasn't actually being sorted in date order. Upon some digging, I found that they were actually being sorted in reverse alphabetical order - it just so happened that we've not broken that pattern of post names since the site launched 😆
In my defense, [the Zola theme I used as reference for implementing this site also makes this mistake...](https://github.com/getzola/hyde/blob/master/templates/index.html#L54)
The fix is to properly sort the `posts` section by date, and then remove the reversing logic from the template. This also has the nice side effect of giving us access to the next/previous post as template variables, so I might integrate that into the template at a later date 😄

Fix sort order on the homepage

---

sass/_extra.scss

Whoops, I forgot the Minima theme doesn't have everything set to `box-sizing: border-box`.
Fixes #76.

Fix box sizing on post images

---

content/posts/newsletter-008/index.md

------
Part of #89 (_"Newsletter 8: Coordination/Tracking"_)

Add gfx-rs org news

---

content/posts/newsletter-009/index.md

Add Shipyard content for newsletter 9

---

content/posts/newsletter-009/index.md

μsfx is a small library built for generating sound effects in code during
runtime. μsfx can be integrated with the `cpal` and `music` crates as well as
`SDL2` crate bindings.
Samples are available on [μsfx's github readme][usfx-github] and further
documentation is avialable on the [docs.rs page][usfx-docsrs].
This latest version (0.1.3) provides fixes for saw, triangle,
and square waves.
[usfx-github]: https://github.com/tversteeg/usfx
[usfx-cratesio]: https://crates.io/crates/usfx
[usfx-docsrs]: https://docs.rs/usfx/0.1.3/usfx/
[Iced][iced-cratesio] is experimental, cross-platform GUI crate focusedd on simplicity and
type safety. Iced can be used natively, in a web browser, or can use wgpu,
The new release includes:
* Styling based on trait implementations.
* Event subscriptions that …

Add iced, usfx, and assets-manager

---

content/posts/newsletter-010/index.md

It's the first time I write something like this, so just point me the issue ;)
@ozkriff asked to link it here #139

Add section about `goods` assets library

---

content/posts/newsletter-010/index.md

Part of https://github.com/rust-gamedev/rust-gamedev.github.io/issues/139.

Add Tetra content for newsletter 10

---

content/posts/newsletter-010/index.md

Newsletter 10: Added Godot content

---

content/posts/newsletter-010/index.md

Preview (6cb7dfb): https://rust-gamedev-preview.netlify.com/posts/newsletter-010
:timer_clock:  Hope to merge this tomorrow +- at 17:00 UTC (in ~20 hrs from now) if there're no objections.
_Part of #139 ("Newsletter 10: Coordination/Tracking")_

Newsletter 10

---

content/posts/newsletter-011/index.md

Hopefully I did this right.
Part of #172

Newsletter 11: yaks

---

content/posts/newsletter-011/index.md

Part of https://github.com/rust-gamedev/rust-gamedev.github.io/issues/172.
May be able to help out with some other sections later in the week, but figured I'd get my stuff out of the way :)

Newsletter 11: Tetra

---

content/posts/newsletter-011/index.md

_Part of #172 ("Newsletter 11: Coordination/Tracking")_

Newsletter 11: Add KatharosTech on GitHub Sponsors

---

.github/workflows/ci.yml
.markdownlint.json
README.md
content/posts/2019-08-18-introducing-the-rust-game-development-working-group.md
content/posts/newsletter-001/index.md
content/posts/newsletter-002/index.md
content/posts/newsletter-003/index.md
content/posts/newsletter-004/index.md
content/posts/newsletter-005/index.md
content/posts/newsletter-006/index.md
content/posts/newsletter-007/index.md
content/posts/newsletter-008/index.md
content/posts/newsletter-009/index.md
content/posts/newsletter-010/index.md
content/posts/newsletter-011/index.md
content/posts/survey-01/index.md

Consistency is King
Closes #30 (_"CI: Add markdownlint check"_)

CI: Add markdownlint

---

content/posts/newsletter-013/index.md

Newsletter 13: Add blitz-path

---

.github/workflows/ci.yml
config.toml
sass/_extra.scss

* Updated the CI to use Zola 0.11
* Fixed an issue with the way the CSS was rendering the new code block markup
* Changed the feed settings to keep the existing behaviour from the previous version (seems a bit pointless to do another redirect if we don't have to)

Update Zola to 0.11

---

content/posts/newsletter-001/index.md
content/posts/newsletter-003/index.md
content/posts/newsletter-004/index.md
content/posts/newsletter-005/index.md
content/posts/newsletter-006/index.md
content/posts/newsletter-007/index.md
content/posts/newsletter-008/index.md
content/posts/newsletter-009/index.md
content/posts/newsletter-010/index.md
content/posts/newsletter-011/index.md
content/posts/newsletter-012/index.md
content/posts/newsletter-013/index.md
newsletter-template.md
sass/_extra.scss

This PR uses a [MD/CSS hack](https://stackoverflow.com/questions/19331362/using-an-image-caption-in-markdown-jekyll) to add centered image captions.
<details><summary>before/after imgs</summary>
<p>
Before:
After:
</p>
</details>

Add centered image captions using MD/CSS hack

---

content/posts/newsletter-013/index.md

@chinedufn r? Should something be changed or added? :)
_Part of #232  ("Newsletter 13")_

Newsletter 13: Akigi

---

content/posts/newsletter-014/index.md
newsletter-template.md

Also, this PR updates the template file.
_Part of #232 ("Newsletter 13")_

N14: Initial draft

---

.github/workflows/ci.yml

I held off on updating to 0.12 cause it was broken on Windows, but the latest patches seem to have fixed that.
I tried building the site with 0.12.2 and it all seems to work without any changes - figured it'd be a good idea to stay up to date, so that contributors don't have to download old versions of Zola.

Update Zola to 0.12.2

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Closes #269 (_"Proper style guide/contributing guidelines"_)

Add contributing guidelines & PR template

---

content/posts/newsletter-015/index.md

_Part of #320 ("Newsletter 15")_

N15: How to: Rust + SDL2 + OpenGL on the web

---

content/posts/newsletter-015/index.md

Part of https://github.com/rust-gamedev/rust-gamedev.github.io/issues/320.
I'm cheating slightly as Tetra 0.5.2 came out a few hours into November :p Hopefully that's okay, I didn't want to have to hold half the update back till next month!

N15: Tetra and ogmo3

---

content/posts/newsletter-015/index.md

Part of #320 ("Newsletter 15")

N15: physme

---

content/posts/newsletter-015/index.md

While reviewing  #361 I noticed this; so I slightly improved the working here so it's a bit easier to parse the sentence.
Please, read the [contributing guidelines][contributing] before submitting a PR.
[contributing]: https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md

Improved wording in rust-gpu description

---

content/posts/newsletter-015/index.md

Added Oxford commas where needed

---

content/posts/newsletter-015/index.md

Preview (https://github.com/rust-gamedev/rust-gamedev.github.io/commit/2a0df9163c0c0492e01061c2a74e5a7ef2665ad8): https://rust-gamedev-preview.netlify.app/posts/newsletter-015
:timer_clock: Hope to merge this today +- at 15:00 UTC (in ~8 hours from now) if there're no objections.
_Part of #320 ("Newsletter 15")_

N15: Release

---

content/posts/newsletter-016/index.md

I didn't really have an image I wanted to use as all the changes have been mostly code based.

N16: Learn Wgpu

---

content/posts/newsletter-017/index.md

This is a tiny fix for #410 - just had a random realization this evening that I forgot to add my co-developer, oops.
Part of #408.

N17: Update description for rpt

---

content/posts/newsletter-017/index.md

Woops, markdown links are sometimes confusing.

Fix 15m santa links in newsletter 17

---

.github/workflows/ci.yml

🤖 🤖 🤖 
One common problem we have with the newsletter each month is misformatted PRs - sometimes people submit them and then don't check whether the build has passed, which means @ozkriff and me have to chase them up. This seemed like it should be a really easy thing to automate, and that turned out to be the case :)
I've tested this PR on a fork of the repo, and it seems to work okay (and it's using an official GitHub action package, so should be reasonably stable). It currently comments every time a PR build fails, but I could limit it to once per PR if we want - what do people think?
I also amended the run conditions for the CI job to not run multiple builds per PR.

Automatically comment if a PR doesn't meet the style guide

---

.github/workflows/ci.yml

D'oh, apparently this [only works if the person raising the PR has write access to the repo](https://github.com/actions/first-interaction/issues/10) - which makes this a bit useless 😢

Revert "Automatically comment if a PR doesn't meet the style guide"

---

content/posts/newsletter-018/index.md

Preview (https://github.com/rust-gamedev/rust-gamedev.github.io/commit/1dc3ebaff81be9964d72ff01b0ef6d13f796d74e): https://rust-gamedev-preview.netlify.app/posts/newsletter-018
:timer_clock: Hope to merge this in an hour or so if there're no objections.
_Part of #455_

N18: Release

---

content/posts/newsletter-019/index.md

N19: Add Distill

---

content/posts/newsletter-019/index.md

Sorry for being late! I hope this can make it into the N19. If not, I'm also fine with submitting it for the next one.
_Part of #496_

Add bevy_egui section

---

content/posts/newsletter-020/index.md

Please, read the [contributing guidelines][contributing] before submitting a PR.
[contributing]: https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md

N20: Tetra

---

content/posts/newsletter-020/index.md

N20: Add a section about bevy_game_template

---

content/posts/newsletter-020/index.md

N20: Add Bevy Cheatbook

---

content/posts/newsletter-020/index.md

N20: smaa-rs

---

content/posts/newsletter-020/index.md

N20: Quinn

---

content/posts/newsletter-020/index.md

Changed SM64JS to sm64js since that's its name in the website, and made some other small changes

N20: sm64js Revision

---

config.toml
static/CNAME

Closes #233 (_"Custom Domain"_)
Related to #586 (_"Shorter URLs + split "posts" into news+blog"_)

Custom Domain: gamedev.rs

---

config.toml
sass/_extra.scss

I'd like to make the site's title shorter & centered because atm it looks kinda weird on mobile.

Center and abbreviate the site's title

---

content/news/021/index.md

Please, read the [contributing guidelines][contributing] before submitting a PR.
[contributing]: https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md

N21: Tetra

---

content/news/021/index.md

N21: Added simple-async-local-executor

---

content/news/021/index.md

Added section about wasm_plugin's latest release

N21: wasm_plugin

---

content/news/021/index.md

N21: nalgebra

---

content/news/021/index.md

For #589 .
Hope it's ok to plug my new sponsor link. :slightly_smiling_face:

N21: Add Bevy Cheatbook (Learning)

---

content/news/021/index.md

I hope it isn't too late to add note for my upcoming game engine.

Add paragraph about Arcana game engine

---

content/news/021/index.md

#589 
Just some style bits @ozkriff picked up on!

N21: Style tweaks

---

content/news/021/index.md

_Part of #589._
Preview: https://suspicious-golick-167fda.netlify.app/news/021
⏲️ Merging this in a few hours if there're no objections.

N21: Release

---

content/news/021/index.md

#589
Didn't spot this until after merging, the italics here get rendered like an image caption...

Fix formatting issue on chip-8-rs

---

.github/PULL_REQUEST_TEMPLATE.md

The current template is somewhat meaningless because:
- a lot of contributors leave the current template text as is
- and CONTRIBUTING.md isn't updated to the actual current guidelines.

PR template: Replace CONTRIBUTING link with link to parent

---

sass/_extra.scss

Minima adds some padding at small screen sizes that doesn't play nice with our centered header.
Before:
After:

Fix misaligned header on mobile

---

content/news/022/index.md

N22: LD48: Rusty MMO in 48 Hours

---

content/news/022/index.md

N22: tobj section

---

content/news/022/index.md

_Part of #640_
Sorry for the delay, busy week!

N22: Tetra

---

content/news/022/index.md

Part of #640
Preview: https://agitated-saha-af60ca.netlify.app/news/022/
Todo:

N22: Release

---

newsletter-template.md

>  would it be a good idea to add that  to the template? We're always having issues with this plugin breaking the TOC, so would be good to disable that

Template: separate tooling and no-toc

---

content/news/023/index.md

_Part of #677 _
Adds an entry for my medium.com article, "Game Development with Rust"

N23: Add Medium.com Rust GameDev Article

---

content/news/023/index.md

N23: Add paragraph about WASM plugins

---

content/news/023/index.md

Preview (https://github.com/rust-gamedev/rust-gamedev.github.io/commit/052d37a2407640f18b3f4edb93af991d262bcd8b): https://rust-gamedev-preview.netlify.app/news/023
:timer_clock: Hope to merge this ~16:00 UTC today (in ~9 hours from this PR creation) if there're no objections.
_Part of #677_

N23: Release

---

content/news/024/index.md

N24: Add discord-sdk

---

content/news/024/index.md

rg3d RPG Tutorial (July Issue)

---

content/news/024/index.md

Subsection on audio refactoring

N24: Macroquad

---

content/news/024/em_logo.svg

_Part of #719_
It's currently weirdly left aligned:

N24: Fix crop on Emerald logo

---

content/news/025/index.md

This changes long changelog bulletpoint sections into paragraphs.

Remove longer changelog sections

---

content/news/027/index.md

Write Sparsey section

---

content/news/028/index.md

N28: Tetra

---

content/news/028/index.md

N28: Pixels

---

content/news/027/index.md
newsletter-template.md

My quick attempt to turn unclaimed sections from https://github.com/rust-gamedev/rust-gamedev.github.io/issues/818 's plan into the "Other News" section (took me something like 30m).
Attempt at #850 (_"\"Other News\" section"_)

N27: "Other News" section

---

content/news/028/index.md

N28: Rust CUDA

---

content/news/028/index.md

_Part of #852_
The linkdrop campaign will be online very soon, so don't worry about the dead link.
I'll probably have something online later today.

n28: shroom kingdom

---

content/news/029/index.md

N29: assets_manager

---

.github/workflows/ci.yml
content/news/016/index.md
content/news/017/index.md
content/news/020/index.md

I'm on the latest version of Zola, and I had to remove these links since Zola appears to now check that anchors lead to somewhere properly. Good feature though!

Fix anchors for Zola 0.15

---

content/news/029/index.md

Add paragraph for rapid-qoi

---

content/news/030/index.md

_Part of #888_
Think this is the last thing we have left to do before we can close off December's tracking issue?

N30: Initial draft

---

content/news/030/index.md

Okay here is my 2nd try. Fixed the lint issues
Went for short and sweat summary. Let me know if there is anything off.  
Part of https://github.com/rust-gamedev/rust-gamedev.github.io/issues/912

N30: Legion to Bevy

---

content/news/030/index.md

N30: Tetra

---

content/news/030/index.md

_Part of #912_
We don't usually fill in the Jobs section, but I've seen various people from Embark tweeting about vacancies in the last few weeks so it seemed worth doing this month. Let me know what you think of the formatting (and whether this should be a regular thing we do?)
Followed @ozkriff's formatting from last month for the discussions section, seemed much cleaner than how I did it last time I was editor :)

N30: Discussions and Jobs

---

content/news/030/index.md

For #912 .
Let me know if this is too much self-promotion.

N30: add Bevy Cheatbook

---

content/news/030/index.md

N30: Add bevy_backroll blurb

---

content/news/030/index.md

In #933 some (imo) important information was removed, to avoid nested bullet points. 
I want to edit the Bevy Cheatbook announcement to better present the list of changes.

N30: edit Bevy Cheatbook (fixup)

---

content/news/031/index.md

N31: Image filters with wgpu-rs

---

content/news/031/index.md

_Part of #949_
[Rendered version](https://agitated-saha-af60ca.netlify.app/news/031/) (bc241e07f806)
Remaining steps:

N31: Release

---

content/news/032/index.md

_Part of #979_
The [`screen-13`](https://github.com/attackgoat/screen-13) library recently got some getting-started documentation. It also received new examples, features, and such.
Thank you!

N32: Add Screen 13 library update

---

content/news/032/index.md

N32: Bevy Jam Analysis

---

content/news/032/index.md

Spelling and grammar fixes for N32

N32: Spelling and Grammar

---

content/news/032/index.md

_Part of #979_
Preview (0839f244f1a5c09ca34438d97c3692e8374162da): https://sharp-aryabhata-9cc78b.netlify.app/news/032/

N32: Release

---

.github/workflows/ci.yml

Noticed while making a change to arewegameyet that we don't need to use a personal access token here any more.

Use built in Github token instead of personal access token

---

.github/workflows/ci.yml

As mentioned on #945, there's an upstream issue with the CI action we use to publish to GitHub Pages where if `keep_history` is set to `true`, files will never be deleted from the `master` branch, even if they're no longer present in Zola's output. The default is `false`, which effectively force pushes to `master` every time, meaning that it will always reflect exactly what was generated by the most recent Zola run.
Given that we never actually utilize the history on the `master` branch (e.g. if we do a revert, we generally just revert on `source` and let the site republish), I don't think there's much value to keeping the history around? I think it would be worth switching back to the default here.

Allow CI to push file deletions (fixes #945)

---

content/news/033/index.md

N33: Other News

---

content/news/013/index.md
content/news/017/index.md
content/news/020/index.md
content/news/024/index.md
content/news/026/index.md
content/news/030/index.md

I've decided to change my username, and with that some links in newsletters I've been featured in have been broken (or will be eventually when they stop redirecting to my new profiles). This patches links to my stuff to point to the right places again.

Replace MoleTrooper -> Molentum; update related links

---

content/news/035/index.md

_Part of #1065_
Will do Extra News as part of the release PR (probably tomorrow).
I left out '[Should game engines have a visual editor?](https://twitter.com/cart_cart/status/1535128838971088898)' from the plan - I don't feel like there was really a call for discussion/feedback in the tweet, so not sure how well it fits the Discussions section.

N35: Discussions, RFCs and Jobs

---

content/news/036/index.md

_Part of https://github.com/rust-gamedev/rust-gamedev.github.io/issues/1098_

N36: add bevy_godot section

---

content/news/036/index.md

Sorry for the last minute change
_Part of #1098_
See https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1115#issuecomment-1208476455

N36: Fix bevy_mod_fbx name

---

content/news/037/index.md

_Part of #1134_
Adds paragraph about upcoming update Edict 0.2

Adds paragraph about Edict 0.2

---

content/news/039/index.md

_Part of #1180_
Adds `presser` section to newsletter 39.

N39: presser

---

content/news/039/index.md

N39: Hanabi

---

content/news/039/index.md

N39: glutin

---

content/news/040/index.md

Part of #1203 November newsletter

N40: Pixel Engine

---

content/news/042/index.md

N42: big-brain

---

content/news/042/index.md

N42:`scene-graph` and `tween`

---

content/news/042/index.md

Improves discoverability for people searching for my work :)
_Part of #1267_

N42: Foxtrot touchup

---

content/news/042/index.md

N42: Update Foxtrot to newest release

---

content/news/044/index.md

N44: Boat Journey: fix fmt

---

content/news/044/index.md

N44: winit-block-on, tinyaudio, faer, bevy hanabi

---

content/news/044/index.md

_Part of #1317_
got rerun entry up-to-date

N44: Update for Rerun 0.5

---

content/news/047/index.md

N47: Rerun update

---

content/news/048/index.md

N48: Mobile development with Bevy

---

content/news/049/index.md

N49: Dexterous Developer

---

.github/create_newsletter_scaffold.sh
.github/newsletter-issue-template.md

Fix newsletter ci formatting

---

.markdownlint.json

Fixes #639 
Additionally removes lint for ul list style.
I'm relaxing our lints massively because I want to streamline the process for potential contributors by reducing as much friction as possible. If the current editors since the revival find the lints too relaxed, I'm very open to changing them in the next release cycle.

Simplify lints

---

content/news/050/index.md

adding bottomless-pit

---

.github/newsletter-issue-template.md
.github/workflows/create-newsletter.yaml

- Remove duplicate title
- Fix outdated lint information
- Remove TODOs
- Add reminders for which places to post the monthly updates on (All of the Discord server's moderation teams have agreed to get these)
- Assign me to some things
- Merge monthly calls for submissions with spreading the released newsletter
- Move the generation of the next newsletter to the publication date
- Adopt the freeze period schedule proposed by @Vrixyz in https://github.com/rust-gamedev/rust-gamedev.github.io/issues/1417#issuecomment-1764534286
From the linked issue, the schedule is as follows:
```mermaid
timeline
title This Month in Rust Gamedev News
3rd : Release previous news entry!
: (Release) social media posts, 
: (Release) links to discussions
: Add a draft of next month's newsletter
4th-27th : …
```

Improve issue template and optimize schedule

---

content/news/050/index.md

Part of https://github.com/rust-gamedev/rust-gamedev.github.io/issues/1474
Please let me know if this works!

Add content for lightyear library

---

.github/workflows/ci.yml

Check for dead links

---

content/news/050/index.md

I noticed some small typos on my previous PR! :)

Fix typos on lightyear

---

content/news/050/index.md

Building Android games

---

content/news/050/index.md

N50 Add commas

---

content/news/050/index.md

Resolves #1474
Scheduled for **2024-05-03**

Release N50

---

content/news/050/index.md

Part of #1474
This is a patch. The github source code is no longer open source the reason is this is cause the code uses private stuff like database, etc.
The currently open source github code is very outdated so m gonna remove it so people dont get confused with the updates on the github client and the actual site (since the server and site now use the secure private repo data)

quick change to the thing i made sm64jsarchive (N50: sm64jsarchive #1474)

---

content/news/051/index.md

N51: RustNL

---

.github/create_newsletter_scaffold.sh
.github/newsletter-template.md

_Part of #1417_
To follow idea from https://github.com/rust-gamedev/rust-gamedev.github.io/issues/1417#issuecomment-1824008515
Not fully tested yet, the ci scripts (date, sed...) are very linux centric so my mac can't run them as-is (I might look into https://github.com/nektos/act, but I'd prefer a granular action to try only parts of those scripts, I wouldn't want to create a commit, issue, etc.

Future news section

---

.github/workflows/ci.yml

The site had some trouble earlier, so I temporarily disabled link checks.

Enable link checks for gamedev.social

---

sass/_extra.scss
static/intro-icons.svg
templates/includes/email_signup.html

Style Email Signup Form

---

content/news/052/index.md
sass/_extra.scss

[Rendered](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/release-52/content/news/052/index.md)
Closes #1523 
Please do not merge before 03.07.2024
If everything goes right, this post will be delivered to a handful of early subscribers per email!

Release N52

---

.github/newsletter-issue-template.md
.github/newsletter-template.md
CONTRIBUTING.md

I'm not particularly attached to H.264 but it's a codec that works well on many popular platforms.
Should close #1518 .

Add doc pointers to the embed_video shortcode

---

templates/shortcodes/embed_video.html
templates/shortcodes/image_figure.html

Fix incorrect order of comments resulting in accidental output

---

.github/workflows/ci.yml

This makes it clearer when merging with failing link check that only the link check failed but the build passed otherwise.

Split link checking into its own job
