_posts/2019-08-18-introducing-the-rust-game-development-working-group.md
That's what I get for copying and pasting...
=> Fix broken link to RSS feed in post

_sass/extra.scss
Fixes #11. Figured I should get this done before the newsletter goes out :)
=> Fix CSS margin issues

_drafts/newsletter-004.md, _posts/2019-11-07-newsletter-003.md
Ugh, #35 added links to the wrong MD file :man_facepalming: 
(upd: also, this PR syncs fu5ha's username)
=> Newsletter 3: Fix discussion links

content/posts/newsletter-004/index.md
r? :)
I'll merge this in an hour If there're no objections.
=> Publish the Fourth Newsletter

sass/_extra.scss
Fixes #76, as requested by @AngelOnFira.
I also removed some unused CSS which got added in #42 by mistake.
Preview:
=> Add some extra styling for images

content/posts/newsletter-007/index.md
> Hard-wrap at 80 chars, please.
------
_Part of #64 ("Newsletter 7: Coordination/Tracking")_
=> Newsletter 7: hard-wrap

.github/workflows/ci.yml
Seems to work fine locally.
Fixes #61 (_"Update to Zola 0.10"_)
=> Zola v0.10

content/posts/newsletter-008/index.md
I'm not the library author but the latest release seems worthy to be included in the newsletter!
------
_Part of #89 ("Newsletter 8: Coordination/Tracking")_
=> Ash 0.30 release

content/posts/newsletter-008/index.md
Part of #89 ("Newsletter 8: Coordination/Tracking")
=> Newsletter 8: miniquad

content/posts/newsletter-009/index.md
_Part of #89 ("Newsletter 8: Coordination/Tracking") and #111 ("Newsletter 9: Coordination/Tracking")
=> Newsletter 9: Initial draft

content/posts/newsletter-009/index.md
Part of #111 (_"Newsletter 9: Coordination/Tracking"_)
=> Add Tetra content for newsletter 9

templates/includes/social.html
=> Fix RSS Link in Site Footer

content/posts/newsletter-010/index.md
Added a "Learning Material Updates" section for tutorial videos, posts, and books.
Part of #111 (_"Newsletter 9: Coordination/Tracking"_)
Part of #139 (_"Newsletter 10: Coordination/Tracking"_)
=> Newsletter 10: Initial draft

content/posts/newsletter-010/index.md
I think this is how it's supposed to be :)
=> Fix iced link

content/posts/newsletter-011/index.md
_Part of #139 ("Newsletter 10: Coordination/Tracking")_
_Part of #172 ("Newsletter 11: Coordination/Tracking")_
=> Newsletter 11: Initial draft

content/posts/newsletter-012/index.md
_Part of #172 ("Newsletter 11: Coordination/Tracking")_
_Part of #201 ("Newsletter 12: Coordination/Tracking")_
=> Newsletter 12: Initial draft

content/posts/newsletter-013/index.md
_Part of #201 ("Newsletter 12: Coordination/Tracking"_)
_Part of #232 ("Newsletter 13"_)
=> Newsletter 13: Initial draft

content/posts/newsletter-015/index.md, newsletter-template.md
=> N15: Initial draft

content/posts/newsletter-015/index.md
=> N15: Akigi

content/posts/newsletter-016/index.md
_Part of #320 ("Newsletter 15")_
=> N16: Initial draft

content/posts/newsletter-016/index.md
=> N16: Survey reminder

content/posts/newsletter-016/index.md
=> N16: winit

content/posts/newsletter-017/index.md
_Part of #365 ("Newsletter 16")_
=> N17: Initial draft

content/posts/newsletter-017/index.md
=> N17: Tetra

content/posts/newsletter-018/index.md
Follow up of #408 ("Newsletter 17")
=> N18: Initial draft

content/posts/newsletter-018/index.md
=> N18: Tetra

content/posts/newsletter-018/index.md
Part of #455 - as spotted by @o2sh here: https://github.com/rust-gamedev/rust-gamedev.github.io/pull/456#issuecomment-771297374
=> N18: Fix Teki hyperlink

content/posts/newsletter-018/index.md
=> N18: LDtk-rs

content/posts/newsletter-019/index.md
This was recently released and isn't in the outline so I figured I'd add a little blurb.
_Part of #496_
=> N19: Add wasm_plugin section

content/posts/newsletter-019/index.md
Preview is here: https://agitated-saha-af60ca.netlify.app/posts/newsletter-019/
(218fbfc)
This will be merged tomorrow, the 8th of March :tada:
Part of #496
=> N19: Release

sass/_extra.scss, sass/minima/_layout.scss
=> minima/_layout.scss: Remove black line on top

content/news/021/index.md
#589 
Whoops, missed these in the original review...
=> N21: Fix some broken links in the WGPU section

content/news/021/index.md
Small fix, updated some macroquad links
=> N21: hotfix macroquad links

content/news/021/index.md
=> N21: Add discussion links

content/news/022/index.md
=> N22: Rust in Unreal update

content/news/022/index.md
=> Added comment links

content/news/024/index.md
=> N24: Initial draft

content/news/024/index.md
=> N24: Add blog post "Asset handling in Bevy apps"

content/news/024/index.md
Last-minute amendment to #745 to include our trailer announcement 🙇
=> Fish Fight trailer

content/news/024/index.md, newsletter-template.md
=> N24: Add discussion links

content/news/025/index.md
=> N25: Initial draft

content/news/024/index.md
Bevy uses E-Good-First-Issue label now
=> Fix Bevy's Good First Issues link

content/news/025/index.md
_Part of #751_
Sorry, I was convinced i checked the links before submitting last time but i clearly haven't.
=> Fix links in N25 RecWars

content/news/025/index.md
=> Discussion links and final fixes

content/news/026/index.md
=> N26: Gamedev Meetup

content/news/018/index.md, content/news/019/index.md, content/news/020/index.md, content/news/021/index.md, content/news/022/index.md, content/news/023/index.md, content/news/024/index.md, content/news/025/index.md
With the change of the Twitch channel name, the link to the channal also changed.
=> Update link of Rust Gamedev Twitch

content/news/027/index.md
_Part of #818_
Netlify preview (a6d3c5f): https://sharp-aryabhata-9cc78b.netlify.app/news/027
=> N27: Release

content/news/027/index.md
_Part of #818_
cc @ozkriff - if you get a sec could you update the pinned tweet on Twitter? That's the one thing I can't do through TweetDeck 😅
=> N27: Add discussion links

content/news/028/index.md
=> N28: Initial draft

content/news/028/index.md
=> N28: Quinn

content/news/028/index.md
=> Fix Quinn links

content/news/028/index.md
=> N28: Add /r/rust_gamedev discussions

content/news/028/index.md
Part of #852 
Netlify Preview (b874f85): https://agitated-saha-af60ca.netlify.app/
Remaining steps:
=> N28: Release

content/news/030/index.md
=> N30: add leafwing-input-manager

content/news/030/index.md
_Part of #912_
**Netlify preview:** https://sharp-aryabhata-9cc78b.netlify.app/news/030/
=> N30: Release

content/news/030/index.md
=> N30: Spelling/grammar pass

content/news/030/index.md
=> N30: Discussion links

content/news/031/index.md
I messed up a version number in the last entry
=> Fix version number

content/news/032/index.md
=> N32: Kira v0.6.0

content/news/032/index.md
#979 
Updated entry for cheaters never win.
- repo link
- mentioned continued development
=> N32: Update Cheaters Never Win

content/news/032/index.md
=> N32: DIMS jobs

content/news/032/index.md
_Part of #979_
I put down 'various roles' for Embark, as they have a lot of vacancies coming and going - seems like they could get out of date fairly quick.
=> N32: Other News and Jobs

content/news/033/index.md
[Rendered version](https://agitated-saha-af60ca.netlify.app/news/033/): 1ca739c
_Part of #1010_
Todo:
=> N33: Release

content/news/034/index.md
=> fix swapped twitter handles

content/news/035/index.md
=> N35: Spelling and grammar

content/news/035/index.md, content/news/036/index.md
=> N35: Discussion links and init for next month

content/news/036/index.md
Mentioned to me by @imberflur, this leads to an archived repo with no issues.
=> Remove Amethyst from "good first issues"

content/news/037/index.md
Hackmd draft of the coordination issue: https://hackmd.io/@gamedev-rs/n37
_Part of #1098_
=> N37: Init + update template

content/news/037/index.md
=> N37: grid_pathfinding

content/news/038/index.md
=> N38: big-brain bump

content/news/039/index.md
small bit on on wgpu wiki update
_Part of #1180_
=> N39: section on wgpu wiki update

content/news/040/index.md
_Part of #1203_
I noticed the link in the heading was broken by mistake after a maintainer made some corrections, so this PR fixes that.
=> Fix bevy_atmosphere v0.5 heading

content/blog/graphics-meetup-02/index.md
This just adds links to the graphics meetup 2 blog post.
=> Graphics Meetup 2 blog YouTube links

content/news/041/index.md
Sorry for being this late
_Part of #1233_
=> N041: Add `assets_manager`

content/news/042/index.md
_Part of #1267_
Hoping to get this released soon!
To review, open the [live site](https://agitated-saha-af60ca.netlify.app/news/042/) (6289fbb), and try and find anything that looks out of place. Leave a comment about it here, and I'll get it fixed!
=> N42: Release

content/news/043/index.md
We managed to snag the Ambient server URL 🎉
_Part of #1287_
=> N43: update Ambient Discord URL

content/news/047/index.md
=> #1401 Other News Updates

content/news/049/index.md
=> N49: Tribes

.github/workflows/create-newsletter.yaml
Fixes permissions when creating a new PR in the newsletter CI
=> Add pull requests permission to create newsletter CI

config.toml
=> Enable smart punctuation

.github/newsletter-template.md
=> Add Mastodon link

content/news/050/index.md
=> N50: review pass for typos/consistency/clarity

content/news/050/index.md
=> Add context for monthly schedule discussion

content/news/050/index.md
=> Release N50 fixes

content/news/050/index.md
forgot to patch these up! sorry :P
(n50 sm64jsarchive #1474 is what im making the patch for)
=> patches (N50: sm64jsarchive #1474)

content/news/052/index.md
=> Release 52 fixes

content/news/052/index.md
=> Add post links

.github/workflows/ci.yml
Whoops, this should work now @janhohenheim
=> Use correct version of upload-pages-artifact action
